"""'password'

Revision ID: 5261889f91e5
Revises: 9f6e2418ddcc
Create Date: 2017-07-25 15:23:55.562176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5261889f91e5'
down_revision = '9f6e2418ddcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
